name: recipe-actions
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build django recipe
        run: docker-compose run app sh -c "python manage.py test && flake8"
